export const TOGGLE_EXPAND_MENU_ITEM = 'TOGGLE_EXPAND_MENU_ITEM'

export const CLOSE_MENU = 'CLOSE_MENU'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const TOGGLE_WITHOUT_ANIMATION = 'TOGGLE_WITHOUT_ANIMATION'

export const SHOW_ERROR_MODAL = 'SHOW_ERROR_MODAL'

export const SHOW_MODAL = 'SHOW_MODAL'

export const SET_USER_DATA = 'SET_USER_DATA'

export const SET_DEPARTMENTS_DATA = 'SET_DEPARTMENTS_DATA'

export const SET_EMPLOYEES_DATA = 'SET_EMPLOYEES_DATA'

export const SET_POSITIONS_DATA = 'SET_POSITIONS_DATA'

export const SET_DEPARTMENT_STATISTICS = 'SET_DEPARTMENT_STATISTICS'

