export const TOGGLE_EXPAND_MENU_ITEM = 'TOGGLE_EXPAND_MENU_ITEM'

export const CLOSE_MENU = 'CLOSE_MENU'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const TOGGLE_WITHOUT_ANIMATION = 'TOGGLE_WITHOUT_ANIMATION'

export const SHOW_ERROR_MODAL = 'SHOW_ERROR_MODAL'

export const SHOW_MODAL = 'SHOW_MODAL'

export const SET_USER_DATA = 'SET_USER_DATA'
